### ISSUE TITLE
Add "Not" Condition Function 

### ISSUE THREAD

**Issue by Znack** [freckle/stratosphere#80]
As I understand it should be quite straightforward to add such a feature because there are already great analogues. If you don't mind I would to open PR and suggest to do it myself, although I'm totally newbie in Haskell world and if you give me some contribution guide, I will do my best to extend stratosphere functionality :) The main question for me: what is the workflow to contribute, for example is there CI tests or run its locally is enough?

Thank you!

**Comment by jdreaver** [comment]
Hey @Znack! Sure, I can help you contribute.

First, you should go to the file for `Stratosphere.Values`. Here it is on Github: https://github.com/frontrowed/stratosphere/blob/master/library/Stratosphere/Values.hs

What we want to do is add the `Not` function to the `Val a` type. Here is the definition of that: https://github.com/frontrowed/stratosphere/blob/a91f4251437b13e067883270e01aa6830a45c8ee/library/Stratosphere/Values.hs#L39-L52

See how all of the intrinsic functions are defined here? We just need to add a constructor for `Not`. I'm pretty sure it would look like:

```haskell
Not (Val Bool)
```

A good place to put it is probably near the other bool functions, like right after `Or`.

Now we need to tell `stratosphere` how to serialize this to JSON. We do that by editing the definition of the `ToJSON (Val a)` and `FromJSON (Val a)` type classes.

https://github.com/frontrowed/stratosphere/blob/a91f4251437b13e067883270e01aa6830a45c8ee/library/Stratosphere/Values.hs#L61-L76

https://github.com/frontrowed/stratosphere/blob/a91f4251437b13e067883270e01aa6830a45c8ee/library/Stratosphere/Values.hs#L91-L114

Look at how some of the other intrinsic functions are defined to get a sense of what is required there.

---

We have a build set up with CircleCI, so don't worry about breaking anything :smile:  I will also review the PR you make of course, and I can provide any guidance you need there too. Let me know if you need more help!

**Comment by Znack** [comment]
Hello, thanks for such detailed answer, I have cloned repo, now everything looks quite clear, and I will start my first attempts to make things working shortly :)

**Comment by Znack** [comment]
Hey @jdreaver! I'm stuck with the next step :)

I did what you describe above, it was pretty easy and I suppose now everything is correct regarding `Not` itself, you can check [this commit](https://github.com/Znack/stratosphere/commit/ed030349e62d7ab35c6b5b957f32abbeacd711ca)

Although when I tried to use it in my project I have encountered the next problem with the code:

```haskell
λ> :t Not (Equals "A" "B")
<interactive>:1:13: error:
    • No instance for (Data.String.IsString Bool)
        arising from the literal ‘"A"’
```
I cannot to use `Not` with the `Equals` that uses `Text` as parameters. What I mean: `Equals` have type:
```
λ> :t Equals
Equals :: Val a -> Val a -> Val a
```
So if we use `Text` as one of the parameters, we will have `Val Text` as a result of the `Equals`. And we cannot pass it to `Not`. As I understand GADT would help here, but unfortunately I found this comment:

```
-- GADTs are cool, but I couldn't get this to work with FromJSON
``` 

😆 Maybe you have some new ideas since you wrote this comment two years ago and now it is possible to make `Value` instance of `FromJSON`? Thank you

**Comment by cdparks** [comment]
@jdreaver if you want the GADT version to work, we could maybe convert between an untyped representation and a typed GADT version like here: http://augustss.blogspot.ie/2009/06/more-llvm-recently-someone-asked-me-on.html

The untyped version is easier to (de)serialize, but then you need a separate "type checking" phase from `UntypedVal -> Maybe (TypedVal a)` and a "type erasing" phase from `TypedVal a -> UntypedVal`.

May not be worth the trouble though. I am a little surprised `Equals` has the type it does. Do we use that anywhere at FR?

**Comment by jdreaver** [comment]
Ahh, darn. Sorry about this, you are right @Znack.

You've correctly identified the root issue here. The type of `Equals` is

```haskell
Equals :: Val a -> Val a -> Val a
```

but we want

```
Equals :: Val a -> Val a -> Val Bool
```

Indeed, we don't usually use these comparison functions at Front Row because we are already in Haskell, so we just do any computation like this in Haskell. Supporting them is definitely important though. I'll try to take a stab at fixing this today.

---

Holy crap @cdparks nice work, thanks! I'm going to see if your solution can work. As long as it is ergonomic to users (i.e. they shouldn't have to care what goes on under the hood), I'm not too worried about how hairy it is to implement.

I wonder if there is a short-term, lower-cost solution like adding some way to coerce `Val a -> Val b`. Then we could keep everything else as-is and just ask folks to coerce their `Val` values. We already have `Val` constructors that are essentially pluck the `a` in `Val a` out of thin air, like `Ref Text` and `GetAtt Text Text`.

Also, the only reason I have `FromJSON` is to help with testing, and for the goal of being able to use `stratosphere` to validate or lint CloudFormation templates. In reality, I don't think the latter is that useful, but having `FromJSON` around for testing is pretty neat. I'm wondering if we could just do without all the `FromJSON` instances and use the GADT without needing any special machinery to implement `FromJSON`.

Lastly, we could just get rid of any `Bool` types in `Val a` since they aren't quite accurate anyway. That means changing

```haskell
And :: Val Bool -> Val Bool -> Val a
Or :: Val Bool -> Val Bool -> Val a
```

to

```haskell
And :: Val a -> Val a -> Val a
Or :: Val a -> Val a -> Val a
```

That still doesn't fix when we _expect_ a `Bool` though (although this wouldn't even work currently if we need a `Val Bool` AFIACT because of the dependence on the `a` type parameter).

Ah, decisions decisions :smile:

**Comment by Znack** [comment]
Yeah, it is looking like I encountered much deeper problem than I expected with `Not` :)

I've read those article (although it is still quite complicated for me and I'm not sure I understood all nuances there). I have also learned much deeper GADTs itself and made some experiments to understand the problem itself. And now I have few stupid questions :)

The main problem with GADTs and FromJSON instances is requirement that parseJSON have to return `Parser (Val a)` but with GADTs in some cases we will return more specific `Parser (Val Bool)` and it is unacceptable? I tried to do it and exactly got the compile-time error: 
```
• Couldn't match type ‘a’ with ‘Bool’
      ‘a’ is a rigid type variable bound by
        the instance declaration
        at /Users/sergey/projects/delivery/deploy-bot/TypedWithGADTOnly.hs:32:10-25
      Expected type: Parser (Val a)
        Actual type: Parser (Val Bool)
```

There are few ways to solve this problem, one is looking like a dirty hack and I  wonder, is it really inappropriate? The method makes us to create `data Hide f = forall a. Hide (f a)` structure that will hide our own `Val` and than create instance of `FromJSON` for its: `instance FromJSON (Hide Val) where ... `. I tried to implement this one, although I was unable to extract the result from Hide after encoding :( Here is my attempt if you are curious (I've just updated gist of @cdparks adding `Hide` class + its instances and updated the `main`):
```haskell
data Hide f =
  forall a. (Show a) =>
            Hide (f a)

class HideFromJSON f where
  hideParseJSON :: Value -> Parser (Hide f)

instance HideFromJSON Val where
  hideParseJSON (Object o) =
    case HashMap.toList o of
      [] -> fail "Empty object as val"
      [("If", o')] -> do
        Hide (If cond t f) <- parseJSON o' :: Parser (Hide (Val))
        pure $ Hide $ If cond t f
      [("And", o')] -> do
        Hide (And x y) <- parseJSON o' :: Parser (Hide (Val))
        pure $ Hide $ And x y
      -- ...

instance HideFromJSON f => FromJSON (Hide f) where
  parseJSON = hideParseJSON

main = do
  putStrLn $ "Typed     | " ++ show typed
  putStrLn $ "Encoded   | " ++ show encoded
  putStrLn $ "Decoded   | " ++ show decoded
  where
    typed =
      List
        [ And (Not (Equals (Int 1) (Int 2))) (Equals (Bool True) (Bool False))
        , Bool False
        ]
    encoded = encode typed
    Just (Hide decoded) = decode encoded :: Maybe (Hide Val)
--             ^ here I've got compile-time error
```
The error itself:
```
• Couldn't match expected type ‘p’ with actual type ‘Val a’
        because type variable ‘a’ would escape its scope
      This (rigid, skolem) type variable is bound by
        a pattern with constructor:
          Hide :: forall (f :: * -> *) a. Show a => f a -> Hide f
```

Anyway there is the second way with converting between an untyped representation and a typed GADT and this will help because now FromJSON can simply always return `Untyped` and there can not be any confusion for the compiler. Although with this method we have to write converter like `typecheck`. 

All this stuff looking extremely interesting for me and I would be glad to assist you to make this done or anyway to follow the PR to learn a lot of useful things about Haskell :) If I can be useful, can you please guide me where to go and which way is more appropriate for Stratosphere?

**Comment by jdreaver** [comment]
Hey @Znack, thanks for all the research on this!

I think we have a few options here:
1. Use a GADT for `Val a` and use one of the methods outlined by you and @cdparks to convert between the untyped and typed representations in `FromJSON (Val a)`
1. Add some way to coerce `Val a -> Val b`
1. Use a GADT but add some "escape hatch" when reading `Val a` to just stuff anything not extremely simple in a `ValJson Value` or something. That is, we almost ignore trying to parse stuff like `Equals` that changes the type of `a`.
1. Use a GADT and _also_ just remove `FromJSON` from `stratosphere` since we don't really need it and I don't know anyone that uses it. This might also decrease compile times, which are pretty high. I had some pipe dreams of building a library/executable on top of `stratosphere` to do linting on CloudFormation templates, but I don't have any plans to actually execute on that.

We've decided to let this issue stew for a bit and not make too hasty of a decision. I hesitate to make the "wrong" decision, make a backwards incompatible change that breaks peoples' code, and then have to fix it with another backwards incompatible change.

---

@MichaelXavier do you have any opinions on this? Do you use any of the boolean intrinsic functions, like `And`, `Equal`, `Or`, etc? Have you had issues with their poor types? We don't use them at Front Row so we've never encountered issues here.

**Comment by Znack** [comment]
Thanks for explanations @jdreaver, it is useful for me to understand the possible approaches here :)

Of course, I understand that such a decision should be considered with a lot of attention and there should be some time to gather a feedback. I will follow the issue and learn the accompanying topics, today I read a lot of articles about the GADTs and hope eventually understand it quite well 😄 

Our use case is quite simple: we use not for SnapshotARN parameter of the RDS and if it is not empty use it. And while the issue is still under development I have already prepare the workaround, I just use plain Aeson `Value`:
```
accompanying
